
    create table tb_client (
       id int8 generated by default as identity,
        birth_date timestamp,
        cpf varchar(255),
        email varchar(255),
        genre int4,
        name varchar(255),
        salario float8,
        telefone varchar(255),
        primary key (id)
    );

    alter table if exists tb_client 
       add constraint UK_tbu74oe5ntiego6pu36jfokha unique (email);    